### ISSUE TITLE
Adding debug mode to build

### ISSUE THREAD

**Issue by jpwidera** [haskell-game/dear-imgui.hs#104]
To debug the C/C++-calls and run in gdb a debug mode would be very handsome.
Something like:

```Cabal
if flag(debug)
  if os(linux)
     ghc-options: -Wall -g -rtsopts -dcore-lint -debug -O0
     cc-options: -g -O0 -fsanitize=address -fno-omit-frame-pointer
  if os(darwin)
    ....
  if os(windows)
   ...
```

**Comment by ocharles** [comment]
Sounds good to me!

**Comment by jpwidera** [comment]
As far as I can see, there are no "free" variables in cabal. Therefore this decision tree has to be repeated for each module. 
Does anyone know any trick? Otherwise I will create a PR with `copy and paste`-sections.

**Comment by dpwiz** [comment]
Try this https://cabal.readthedocs.io/en/latest/cabal-package.html#common-stanzas

**Comment by dpwiz** [comment]
@jpwidera Is the issue resolved with compiler flags merged?

**Comment by jpwidera** [comment]
Yes! :)
