### ISSUE TITLE
Add compile-time config

### ISSUE THREAD

**Issue by dpwiz** [haskell-game/dear-imgui.hs#115]
https://github.com/ocornut/imgui/blob/master/imconfig.h

> A) You may edit imconfig.h (and not overwrite it when updating Dear ImGui, or maintain a patch/rebased branch with your modifications to it)
> B) or '#define IMGUI_USER_CONFIG "my_imgui_config.h"' in your project and then add directives in your own file without touching this template.

**Comment by chekoopa** [comment]
I've found a few ways of implementation.

We could incorporate some of these options through flags. It is definitely global, yet AFAIK only acceptable for boolean options. I don't know how to send string values through Cabal configuration.

```cabal
flag wchar32
  description:
    Use 32-bit integer to represent Unicode characters.
  default:
    False
  manual:
    True

if flag(wchar32)
  cxx-options: -DIMGUI_USE_WCHAR32
```

2. We could embed these defines right into the code. Writing defines into C-blocks is very dirty (and useless) approach, so we have `C.verbatim`. I'm afraid that it won't work globally (`IMGUI_USER_CONFIG` is used under `#pragma once` somewhere in the library code)...

```haskell
C.verbatim "#define IM_ASSERT(_EXPR) ((void)(_EXPR))"
```

3. ...But! If we somehow guess the name of the output file corresponding to `DearImGui.Config` module, set it as `IMGUI_USER_CONFIG` in Cabal configuration, we could use `ifdef` and `verbatim`s. But still, no string options.

**Comment by dpwiz** [comment]
Alternatively, we can turn on full unicode support globally.

This looks like a right thing to do by default. Optimisations can follow later.
