### ISSUE TITLE
Update to imgui 1.88

### ISSUE THREAD

**Issue by Drezil** [haskell-game/dear-imgui.hs#150]
Last time i accidentally had checked out the wrong branch on imgui locally (using master instead of v1.87) it compiled flawlessly.

However there is at least one "breaking" change i am aware of when the new implot-version broke my generator:
https://github.com/epezent/implot/blob/master/implot.h#L545-L552
```haskell
#if (IMGUI_VERSION_NUM < 18716) // Renamed in 1.88
#define ImGuiModFlags       ImGuiKeyModFlags
#define ImGuiModFlags_None  ImGuiKeyModFlags_None
#define ImGuiModFlags_Ctrl  ImGuiKeyModFlags_Ctrl
#define ImGuiModFlags_Shift ImGuiKeyModFlags_Shift
#define ImGuiModFlags_Alt   ImGuiKeyModFlags_Alt
#define ImGuiModFlags_Super ImGuiKeyModFlags_Super
#endif
```

according to imgui:
https://github.com/ocornut/imgui/blob/v1.88/imgui.cpp#L390-L392
```
 - 2022/04/05 (1.88) - inputs: renamed ImGuiKeyModFlags to ImGuiModFlags. Kept inline redirection enums (will obsolete). This was never used in public API functions but technically present in imgui.h and ImGuiIO.
```

but i think the dear-imgui-generator we use for the enums generated & exposed them.

So i'm hesitant to just open a PR with "just checkout v1.88 - what could possible go wrong"-mentality :D

**Comment by dpwiz** [comment]
I ran all the examples and everything seems to be working.
