### ISSUE TITLE
ways to reduce superflous cpu usage?

### ISSUE THREAD

**Issue by cartazio** [haskell-game/dear-imgui.hs#187]
I noticed that the demo app was using ~ 86% of a cpu core, 
on the chance that its because of the default renderloop never sleeping, i added a `threadDelay 10_000` to the end of the loop and my CPU usage went down to like ~ 15%. I also disabled Idle gc for now (yeolde +RTS I0 flage)

I think the "at scale" approach is probably using sleeping semantics that wakeup either after an idle period or when inputs over a large enough time interval to debounce or whatever "simultaneous keys" is done, probably using MVars or STM. But what are suggested best practices?

**Comment by dpwiz** [comment]
Check if it has ridiculous amount of FPS. Looks like you have vsync disabled or something.

I just checked the vulkan demo and it uses MAILBOX presentation for no good reason.

**Comment by ocharles** [comment]
The suggest best practice is to [fix your timestep](https://www.gafferongames.com/post/fix_your_timestep/)

**Comment by cartazio** [comment]
So guard the rendering part of the interaction loop with a timer
constraint? I’m not doing game physics, I just don’t want to do renders
unless there’s been data changes.  I’ll play around with the mvar/tvar
stuff I was thinking of doing. Or am I missing something?

**Comment by ocharles** [comment]
@cartazio I actually removed that comment as it's really more about predictable physics. But in general, you don't really want to render as fast as possible. It's more typical to use something like VSync to synchronise your loop to the monitor's refresh rate, or to simply cap FPS artificially.

**Comment by cartazio** [comment]
Yes. I know. I’m asking about what software patterns people use to make the
render thread take steps only when there’s some work to be done.

**Comment by cartazio** [comment]
I’m currently doing stuff with explicit thread delay 10ms , but that’s less
than ideal.  I believe there may be a more work optimal strategy using
mvars or stm data structures.

**Comment by dpwiz** [comment]
`dirty :: MVar ()` should be enough for SDL.

But `dear-imgui`, being an immediate mode gui, requires a constant rate of ticks/updates since it handles its input in the moment.

Maybe I'm wrong on this. Try setting your delay to 10 seconds instead and see if UI still works. If it is, then you can employ that flag var.

**Comment by cartazio** [comment]
I’ll have a look, my fuzzy understanding is that dearimgui
While having an immediate mode api, actually does a diff for determining
what to change each time you do

**Comment by cartazio** [comment]
so definitely doesn't update the gui until the next draw call, so 100ms is probably the slowest thats tolerable

**Comment by dpwiz** [comment]
You can make window events flip a "dirty" flag that would trigger a new frame, maybe with a small [debounce](https://hackage.haskell.org/package/auto-update-0.1.6/docs/Control-Debounce.html) to prevent burning CPU on every pixel a cursor had traveled.

**Comment by cartazio** [comment]
Yeah I see now , I’d have a thread used the sdl2 event apis

**Comment by YellowOnion** [comment]
A quick option is to just grab the display mode and convert that to a thread delay.

**Comment by dpwiz** [comment]
Anyway... I don't think `dear-imgui` can do something here as frame rate is governed by a presentation/windowing framework, picked and configured by user.

**Comment by ad-si** [comment]
@cartazio Did you find a good software pattern?

**Comment by cartazio** [comment]
I think i chose a delay corresponding with 60fps.

For a more complex application I’d have application logic and gui
code/render loop in distinct threads and have some timer based loop for
render calls
