### ISSUE TITLE
[SDL] Add ImGui functions that use the SDL2 Renderer

### ISSUE THREAD

**Issue by barbafh3** [haskell-game/dear-imgui.hs#191]
I am trying to add ImGui to a small project I had using SDL but it didn't seem compatible with what this package offered. I looked at the original C++ project and they seem to have functions that allow rendering using the SDL renderer. I tried adding these binding on my own as in these functions:
```haskell
sdl2InitForRenderer :: MonadIO m => Window -> Renderer -> m Bool
sdl2InitForRenderer (Window windowPtr) (Renderer rendererPtr) = liftIO do
  (0 /=) <$> [C.exp| bool { ImGui_ImplSDL2_InitForSDLRenderer((SDL_Window*)$(void* windowPtr), (SDL_Renderer*)$(void* rendererPtr)) } |]

sdl2RendererInit :: MonadIO m => Renderer -> m Bool
sdl2RendererInit (Renderer rendererPtr) = liftIO do
  (0 /=) <$> [C.exp| bool { ImGui_ImplSDLRenderer2_Init((SDL_Renderer*)$(void* rendererPtr)) } |]

sdl2RendererNewFrame :: MonadIO m => m ()
sdl2RendererNewFrame = liftIO do
  [C.exp| void { ImGui_ImplSDLRenderer2_NewFrame(); } |]

sdl2RendererShutdown :: MonadIO m => m ()
sdl2RendererShutdown = liftIO do
  [C.exp| void { ImGui_ImplSDLRenderer2_Shutdown(); } |]

sdl2RendererRenderDrawData :: MonadIO m => DrawData -> m ()
sdl2RendererRenderDrawData (DrawData drawDataPtr) = liftIO do
  [C.exp| void { ImGui_ImplSDLRenderer2_RenderDrawData((ImDrawData*) $( void* drawDataPtr )); } |]
```
 by i cant seem to get the ImGui window to show properly, the blue bars bug out and the text doesn't show. Since I'm not that savvy in neither cpp, haskell or either library, I though it would be best to ask for their implementation here.

**Comment by ocharles** [comment]
Have you looked at https://github.com/haskell-game/dear-imgui.hs/blob/main/examples/sdl/Image.hs?
