### ISSUE TITLE
Failed to compile shader

### ISSUE THREAD

**Issue by ad-si** [haskell-game/dear-imgui.hs#192]
I was building a minimal example based on the code in the readme: https://github.com/ad-si/dear-imgui-test (Only changes: using OpenGL3).

However, it just opens a blank black screen and I'm getting following error:

```txt
$ stack run
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader! With GLSL: #version 150

ERROR: 0:1: '' :  version '150' is not supported

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader! With GLSL: #version 150

ERROR: 0:1: '' :  version '150' is not supported

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! With GLSL #version 150

ERROR: One or more attached shaders not successfully compiled
```

My system:

```
OS: macOS 13.6.2 22G320 arm64
Host: MacBookPro18,3
Kernel: 22.6.0
CPU: Apple M1 Pro
GPU: Apple M1 Pro
Memory: 3127MiB / 16384MiB
```

**Comment by dpwiz** [comment]
You're using [defaultOpenGL](https://hackage.haskell.org/package/sdl2-2.5.5.0/docs/SDL-Video-OpenGL.html#v:defaultOpenGL) context, which states `glProfile = Compatibility Normal 2 1` and you need 3.2 for shaders v1.5

**Comment by ad-si** [comment]
Thanks! `glProfile = Core Normal 3 2` fixed it for me
