### ISSUE TITLE
text (ImGui::Text) is not formatted

### ISSUE THREAD

**Issue by dpwiz** [haskell-game/dear-imgui.hs#45]
The original uses variable args, but the bindings pass text as a single argument.

```
[C.exp| void { Text("%s", $(char* textPtr)) } |]
```

Either some type trickery is in order, or documentation tweak.

**Comment by ocharles** [comment]
It's intentional that we use variable arguments, see https://github.com/haskell-game/dear-imgui.hs/pull/6. I believe without this this library doesn't build on macOS.

**Comment by dpwiz** [comment]
Ah, yes. It's just the documentation says "Formatted text" when no formatting actually happens.

**Comment by ocharles** [comment]
I think that's just copy/pasted from `imgui.h`

**Comment by dpwiz** [comment]
Settled in f5843195770e4ffd1879ab3cdb9a7cd372fc0d83.
