### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by andreabedini** [haskell-game/dear-imgui.hs#50]
Hi all,

thanks for your work! Is there any chance to have the package relased on Hackage? Any blockers?

Thanks,
Andrea

**Comment by dpwiz** [comment]
The internals are still in flux and there's some CI legwork to be done for uploading docs.

Meanwhile, both cabal and stack projects may use it with git urls.
And... I doubt it would appear on stackage snapshots, so one would have to set their dependencies explicitly anyway.

What are the benefits you see from having the package uploaded? Visibility, haddocs,... anything else?

**Comment by ocharles** [comment]
For me the most important signal from a release is "we're confident in what we've done". We're close to that point, but I don't think quite there yet

**Comment by andreabedini** [comment]
Thank you @dpwiz and @ocharles.

Is there an issue to track the required CI legwork? I will see if I can help.

Unfortunately cabal doesn't pull submodules so pointing `source-repository-package` to GitHub doesn't work for the moment. See https://github.com/haskell/cabal/issues/5536.

I'll work from a local checkout to the time being.

**Comment by dpwiz** [comment]
This is sad indeed.

@ocharles Let's set up a package with a version like 0.0.210421.0 and all the warning signs. This should hurt nobody and benefit some.

**Comment by dpwiz** [comment]
Uh-oh. C++ code is missing in sdist.

**Comment by andreabedini** [comment]
🥳
