### ISSUE TITLE
Example "test" segfaults after start

### ISSUE THREAD

**Issue by dpwiz** [haskell-game/dear-imgui.hs#67]
In 1d6b7cc97be6973d46aac84f74a881549f39d9cc

**Comment by jpwidera** [comment]
I'm not sure, but maybe this is somehow related to a missing default value.

[setNextWindowPos](https://github.com/haskell-game/dear-imgui.hs/blob/cede825dff9f143171da4b15d4600680bf6a9fb4/src/DearImGui.hs#L1373) is calling [Raw.setNextWindowPos posPtr cond nullPtr](https://github.com/haskell-game/dear-imgui.hs/blob/cede825dff9f143171da4b15d4600680bf6a9fb4/src/DearImGui/Raw.hs#L1089) and this itself is calling [SetNextWindowPos(const ImVec2& pos, ImGuiCond cond = 0, const ImVec2& pivot = ImVec2(0, 0));](https://github.com/ocornut/imgui/blob/e3e1fbcf025cf83413815751f7c33500e1314d57/imgui.h#L360). There the nullptr is not replaced by the default argument.

I guess, in the Raw.setNextWindowPos:
`setNextWindowPos :: (MonadIO m) => Ptr ImVec2 -> ImGuiCond -> Ptr ImVec2 -> m ()
setNextWindowPos posPtr cond pivotPtr = liftIO do
  [C.exp| void { SetNextWindowPos(*$(ImVec2* posPtr), $(ImGuiCond cond), *$(ImVec2* pivotPtr)) } |]
`
The transformation from nullPtr to *$(ImVec2* pivotPtr)) casts the void to a ImVec2 and therefore is creating a non-valid memory position.

**Comment by jpwidera** [comment]
A quick Maybe fix can solve this problem:
```
setNextWindowPos :: (MonadIO m) => Ptr ImVec2 -> ImGuiCond -> Maybe (Ptr ImVec2) -> m ()
setNextWindowPos posPtr cond Nothing = liftIO do
  [C.exp| void { SetNextWindowPos(*$(ImVec2* posPtr), $(ImGuiCond cond)) } |]
setNextWindowPos posPtr cond (Just pivotPtr) = liftIO do
  [C.exp| void { SetNextWindowPos(*$(ImVec2* posPtr), $(ImGuiCond cond), *$(ImVec2* pivotPtr)) } |]
```

And the call from setNextWindowPos becomes:
```
      Just pivotRef -> do
        pivot <- get pivotRef
        print pivot
        with pivot $ \pivotPtr ->
          Raw.setNextWindowPos posPtr cond (Just pivotPtr)
      Nothing -> do
        putStrLn "Nothing"
        Raw.setNextWindowPos posPtr cond Nothing
```

**Comment by dpwiz** [comment]
So, default value is not null, but a static pointer :thinking: Good catch!

**Comment by dpwiz** [comment]
It works now!
